config/routes.rb
Test::Application.routes.draw do
  root to: 'posts#index'

  get 'log_out' => 'sessions#destroy', as: 'log_out'
  get 'sign_up' => 'users#new', as: 'sign_up'
  get 'log_in' => 'sessions#new', as: 'log_in'
  resources :posts
  resources :users, exclude: :new
  resources :sessions, exclude: [:new, :destroy]

end

app/models/image.rb
class Image < ActiveRecord::Base
  attr_accessible :url
  
  belongs_to :imageable, polymorphic: true
end
# == Schema Information
#
# Table name: images
#
#  id             :integer(4)      not null, primary key
#  url            :string(255)
#  imageable_id   :integer(4)
#  imageable_type :string(255)
#  created_at     :datetime        not null
#  updated_at     :datetime        not null
#

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :published_at, :title
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :birthday, :email, :first_name, :last_name, :password, :password_confirmation, :username

  attr_accessor :password
  before_save :encrypt_password

  validates_confirmation_of :password
  validates :username, :email, :password, presence: true
  validates :username, :email, uniqueness: true
  validates :password, length: { minimum: 8 }
  validates_format_of :email, with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/

  has_many :posts
  has_many :images, as: :imageable

  scope :adults, -> { where('birthday >= ?', Date.today - 18.years) }

  def full_name
    "#{first_name} #{last_name}"
  end

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end
# == Schema Information
#
# Table name: users
#
#  id            :integer(4)      not null, primary key
#  first_name    :string(255)
#  last_name     :string(255)
#  username      :string(255)
#  password_hash :string(255)
#  password_salt :string(255)
#  email         :string(255)
#  birthday      :datetime
#  created_at    :datetime        not null
#  updated_at    :datetime        not null
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :check_auth, only: %i[new create edit update destroy]
  before_filter :find_post, only: %i[edit update destroy show]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = current_user.posts.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.'  }
      format.json { head :no_content }
    end
  end

  private

  def authorize_user!
    redirect_to log_in_path
    flash[:error] = 'Invalid credentials'
  end

  def can_edit?(post)
    params[:action] == 'show' || post.user_id == current_user.id
  end

  def find_post
    @post = Post.find(params[:id])
    authorize_user! unless can_edit? @post
  end

  def check_auth
    authorize_user! unless current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      session[:user_id] = @user.id
      redirect_to root_url, notice: 'Logged in!'
    else
      flash[:error] = 'Invalid email or password'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => 'Signed up!'
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Test</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="collapse navbar-collapse navbar-inverse">
  <form class="form-inline">
    <div id="user_nav">
      <ul class="nav navbar-nav navbar-left">
        <li><%= link_to 'Posts', posts_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
            <li class="text-muted">
              <%= link_to current_user.email, '#' %>
            </li>

            <li class="text-muted">
              <%= link_to 'Log out', log_out_path %>
            </li>
        <% else %>
            <li class="text-muted">
              <%= link_to 'Log In', log_in_path %>
            </li>
            <li class="text-muted">
              <%= link_to 'Sign Up', sign_up_path %>
            </li>
        <% end %>
      </ul>
    </div>
  </form>
</nav>
<div class="container" >
  <% flash.each do |name, msg|%>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
          <button class="close" type="button" data-dismiss="alert" >
            <span aria-hidden="true">&times;</span>
            <span class="sr-only">Close</span>
          </button>
          <%= msg %>
          <script>
              setTimeout("$('.alert').fadeOut('slow')", 3000);
          </script>
      <%end%>
  <%end%>
  <%= yield %>
</div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :published_at %><br />
    <%= f.datetime_select :published_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<body align="center">
<h1>Listing posts</h1>

<table align="center" class="table">
  <thead>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th>Published at</th>
    <th>Show</th>
    <th>Edit</th>
    <th>Destroy</th>
  </tr>
  </thead>

<% @posts.each do |post| %>
  <tr>
    <th scope="row"><%= post.title %></th>
    <th><%= post.body %></th>
    <th><%= post.published_at %></th>
    <th><%= link_to 'Show', post, class: 'btn btn-success'  %></th>
    <th><%= link_to 'Edit', edit_post_path(post), class: 'btn btn-warning' %></th>
    <th><%= link_to 'Destroy', post, class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %></th>
  </tr>
<% end %>
</table>

<br />
  <%= link_to 'New Post', new_post_path, class: 'btn btn-info' %>
</body>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p class="well">
  <b>Title:</b>
  <%= @post.title %>
</p>

<p class="well">
  <b>Body:</b>
  <%= @post.body %>
</p>

<p class="well">
  <b>Published at:</b>
  <%= @post.published_at %>
</p>


<%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-warning'  %> |
<%= link_to 'Back', posts_path, class: 'btn btn-inverse'%>

app/views/users/new.html.erb
  <div class="row">
    <div class="col-xs-offset-4 col-xs-4">
      <h1 align="center">Sign Up</h1>

      <%= form_for @user do |f| %>
        <% if @user.errors.any? %>
          <div class="alert alert-danger" role="alert">
            <h2>Form is invalid</h2>
            <ul>
              <% for message in @user.errors.full_messages %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="input-group">
            <span class="input-group-addon"><span class="glyphicon glyphicon-user" aria-hidden="true"></span></span>
            <%= f.text_field :first_name , class: 'form-control', placeholder: 'First Name' %>
        </div>
        <div class="input-group">
          <span class="input-group-addon"><span class="glyphicon glyphicon-user" aria-hidden="true"></span></span>
          <%= f.text_field :last_name, class: 'form-control', placeholder: 'Last Name' %>
        </div>
        <div class="input-group">
          <span class="input-group-addon"><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span></span>
          <%= f.text_field :birthday, class: 'form-control', placeholder: 'Birthday' %>
        </div>
        <div class="input-group">
          <span class="input-group-addon"><span class="glyphicon glyphicon-font" aria-hidden="true"></span></span>
          <%= f.text_field :username, class: 'form-control', placeholder: 'Username' %>
        </div>
        <div class="input-group">
          <span class="input-group-addon"><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span></span>
          <%= f.text_field :email, class: 'form-control', placeholder: 'E-mail' %>
        </div>
        <div class="input-group">
          <span class="input-group-addon"><span class="glyphicon glyphicon-lock" aria-hidden="true"></span></span>
          <%= f.password_field :password, class: 'form-control', placeholder: 'Password' %>
        </div>
        <div class="input-group">
          <span class="input-group-addon"><span class="glyphicon glyphicon-lock" aria-hidden="true"></span></span>
          <%= f.password_field :password_confirmation, class: 'form-control', placeholder: 'Password Confirmation' %>
        </div>
        <p><%= f.button 'Create user' , class: 'btn btn-primary btn-block'%></p>
      <% end %>
    </div>
  </div>

app/views/users/posts.html.erb
<% @posts.each do |post| %>
  <%= post.inspect %>
<% end %>